"""
UTILIZAR NOSSA IMAGINAÇÃO

UTILIZAR O PODER DE ARGUMENTAÇÃO

PERGUNTAR PARA A LIDIANE SOBRE OS LIMITES DO RACICIO

FOCAR NO RACIOCIO LÓGICO DA QUESTÃO

EXPLICAR A LÓGICA

NÃO É OBRIGATÓRIO UTILIZAR CODIGO

NÃO SE ATRASAR PARA BAIXAR SEU MATERIAL DA WEB

TRAZER UM PEN DRIVE

COLOCAR NO GOOGLE DRIVE
"""